name: test-artifact

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dummy file
        run: echo "test" > test.txt

      - name: Upload dummy artifact
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: test.txt
