name: Regression suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 2 * * *'
      
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13.3'   # ← Updated here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --html=report.html

      - name: List files (debug)
        run: ls -la

      - name: Upload report
        uses: actions/upload-artifact@v3.1.3
        with: 
          name: pytest-report
          path: report.html
